tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ''
      user: ''
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: ''
      user: 'sawansabbu'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh

elementary:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ''
      user: 'sawansabbu'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: elementary
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: ''
      user: ''
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: elementary_prod
      warehouse: tasty_bytes_dbt_wh